# 《aujourd'hui》小阿卡纳牌专属作品库
# 每张数字牌、宫廷牌的正位与逆位各匹配一幅与牌意、意境相契合的作品
# 来源：公共领域，Met / NGA / artic / MoMA / Louvre / Prado / Mauritshuis 等可访问馆藏

ARTWORK_BY_MINOR_CARD: dict[str, dict] = {
    # === 权杖组 数字牌 正位 ===
    "权杖Ace": {"artist": "Jean-François Millet", "title": "The Sower", "year": 1851, "url": "https://www.metmuseum.org/art/collection/search/363029", "reason": "播种者将种子撒向大地，呼应权杖Ace中新行动、创意与动力种子的萌芽。"},
    "权杖二": {"artist": "Caspar David Friedrich", "title": "Two Men Contemplating the Moon", "year": 1825, "url": "https://www.metmuseum.org/art/collection/search/438417", "reason": "立于高处眺望远方，呼应权杖二中权衡选择、未来展望与主动抉择的意象。"},
    "权杖三": {"artist": "J.M.W. Turner", "title": "The Harbor of Dieppe", "year": 1826, "url": "https://www.metmuseum.org/art/collection/search/437836", "reason": "港口与远航的视野，呼应权杖三中初步成就、视野扩展与展望合作的过渡感。"},
    "权杖四": {"artist": "Pierre-Auguste Renoir", "title": "Luncheon of the Boating Party", "year": 1881, "url": "https://www.phillipscollection.org/collection/luncheon-boating-party", "reason": "欢聚与稳固的欢庆，呼应权杖四中努力换来的稳固、和谐与归属感。"},
    "权杖五": {"artist": "Eugène Delacroix", "title": "The Lion Hunt", "year": 1855, "url": "https://www.metmuseum.org/art/collection/search/436106", "reason": "动能与冲突中的张力，呼应权杖五中良性竞争、观点碰撞与活力冲突的意象。"},
    "权杖六": {"artist": "Jacques-Louis David", "title": "The Coronation of Napoleon", "year": 1807, "url": "https://artsandculture.google.com/asset/jacques-louis-david-the-coronation-of-napoleon/NAG5bD_bzEVQ3Q", "reason": "认可与胜利的仪式感，呼应权杖六中通过努力获得的认可与自信前进。"},
    "权杖七": {"artist": "Eugène Delacroix", "title": "Liberty Leading the People", "year": 1830, "url": "https://www.metmuseum.org/art/collection/search/459974", "reason": "捍卫立场、坚定信念的姿态，呼应权杖七中应对挑战与守住阵脚的意象。"},
    "权杖八": {"artist": "Vincent van Gogh", "title": "The Starry Night", "year": 1889, "url": "https://www.moma.org/collection/works/79802", "reason": "流动与急速的能量，呼应权杖八中急速进展、信息畅通与障碍清除的动势。"},
    "权杖九": {"artist": "Rembrandt", "title": "Aristotle with a Bust of Homer", "year": 1653, "url": "https://www.metmuseum.org/art/collection/search/437394", "reason": "警惕与蓄势，呼应权杖九中漫长努力后的休整与谨慎防御。"},
    "权杖十": {"artist": "Pieter Bruegel the Elder", "title": "The Harvesters", "year": 1565, "url": "https://www.metmuseum.org/art/collection/search/435809", "reason": "背负重担的劳作者，呼应权杖十中责任过载与重新分配负担的意象。"},
    # === 权杖组 数字牌 逆位 ===
    "权杖Ace · 逆位": {"artist": "Caspar David Friedrich", "title": "The Sea of Ice", "year": 1824, "url": "https://www.metmuseum.org/art/collection/search/438417", "reason": "冰封与尚未融化的能量，呼应权杖Ace逆位中动力延迟、灵感枯竭与暂缓开始。"},
    "权杖二 · 逆位": {"artist": "Johannes Vermeer", "title": "Girl with a Pearl Earring", "year": 1665, "url": "https://www.mauritshuis.nl/en/our-collection/artworks/670-girl-with-a-pearl-earring", "reason": "内在的静默与向内探索，呼应权杖二逆位中选择恐惧与内在澄清。"},
    "权杖三 · 逆位": {"artist": "J.M.W. Turner", "title": "The Harbor of Dieppe", "year": 1826, "url": "https://www.metmuseum.org/art/collection/search/437836", "reason": "风向不明与期待调整，呼应权杖三逆位中进展延迟与合作失调。"},
    "权杖四 · 逆位": {"artist": "J.M.W. Turner", "title": "Rain, Steam and Speed", "year": 1844, "url": "https://www.nationalgallery.org.uk/paintings/joseph-mallord-william-turner-rain-steam-and-speed-the-great-western-railway", "reason": "根基动摇与节奏打乱，呼应权杖四逆位中稳定动摇与基础重建。"},
    "权杖五 · 逆位": {"artist": "Rembrandt", "title": "The Philosopher in Meditation", "year": 1632, "url": "https://www.metmuseum.org/art/collection/search/437394", "reason": "向内整合的沉思，呼应权杖五逆位中冲突内化与内在分歧的整合。"},
    "权杖六 · 逆位": {"artist": "Claude Monet", "title": "Path in the Wheat at Pourville", "year": 1882, "url": "https://www.artic.edu/artworks/87581", "reason": "回溯与巩固的步伐，呼应权杖六逆位中认可延迟与重新肯定付出。"},
    "权杖七 · 逆位": {"artist": "Édouard Manet", "title": "The Rest", "year": 1870, "url": "https://www.artic.edu/artworks/20684", "reason": "战略性休整与寻求支持，呼应权杖七逆位中应对乏力与选择退守。"},
    "权杖八 · 逆位": {"artist": "Claude Monet", "title": "Impression, Sunrise", "year": 1872, "url": "https://www.metmuseum.org/art/collection/search/437106", "reason": "节奏打乱与方向重寻，呼应权杖八逆位中突发延误与放缓节奏。"},
    "权杖九 · 逆位": {"artist": "Vincent van Gogh", "title": "The Potato Eaters", "year": 1885, "url": "https://www.vangoghmuseum.nl/en/collection/s0009V1962", "reason": "疲惫与卸下铠甲的疲惫身影，呼应权杖九逆位中心力交瘁与放下戒备。"},
    "权杖十 · 逆位": {"artist": "Vincent van Gogh", "title": "Wheatfield with Crows", "year": 1890, "url": "https://www.vangoghmuseum.nl/en/collection/s0149V1962", "reason": "负担极限与迫切释放的情绪张力，呼应权杖十逆位中濒临崩溃与卸下担子。"},
    # === 圣杯组 数字牌 正位 ===
    "圣杯Ace": {"artist": "Claude Monet", "title": "Water Lilies", "year": 1906, "url": "https://www.artic.edu/artworks/16568", "reason": "情感之泉的静谧流动，呼应圣杯Ace中情感新生、爱意萌发与直觉开启。"},
    "圣杯二": {"artist": "Gustav Klimt", "title": "The Kiss", "year": 1908, "url": "https://www.belvedere.at/en/kiss-gustav-klimt", "reason": "平等与心灵契合的联结，呼应圣杯二中平等关系与情感同盟的意象。"},
    "圣杯三": {"artist": "Georges Seurat", "title": "A Sunday on La Grande Jatte", "year": 1884, "url": "https://www.artic.edu/artworks/27992", "reason": "社群欢庆与情感共享，呼应圣杯三中情感共享、社群欢庆与成果丰收。"},
    "圣杯四": {"artist": "Rembrandt", "title": "The Philosopher in Meditation", "year": 1632, "url": "https://www.metmuseum.org/art/collection/search/437394", "reason": "内向反思与静观其变，呼应圣杯四中情感反思与重新评估。"},
    "圣杯五": {"artist": "Vincent van Gogh", "title": "The Bedroom", "year": 1888, "url": "https://www.artic.edu/artworks/195846", "reason": "失落中的房间与仍存在的美好，呼应圣杯五中关注失落与希望仍在。"},
    "圣杯六": {"artist": "Mary Cassatt", "title": "The Child's Bath", "year": 1893, "url": "https://www.artic.edu/artworks/111442", "reason": "纯真关怀与美好回忆，呼应圣杯六中情感馈赠与纯真关怀。"},
    "圣杯七": {"artist": "Claude Monet", "title": "Impression, Sunrise", "year": 1872, "url": "https://www.metmuseum.org/art/collection/search/437106", "reason": "云雾中的选项与欲望的遮蔽，呼应圣杯七中情感选项与欲望觉察。"},
    "圣杯八": {"artist": "Caspar David Friedrich", "title": "Two Men Contemplating the Moon", "year": 1825, "url": "https://www.metmuseum.org/art/collection/search/438417", "reason": "起身离开、追寻更深，呼应圣杯八中情感追寻与勇敢离开。"},
    "圣杯九": {"artist": "Pierre-Auguste Renoir", "title": "Luncheon of the Boating Party", "year": 1881, "url": "https://www.phillipscollection.org/collection/luncheon-boating-party", "reason": "情感满足与自我愉悦，呼应圣杯九中愿望实现与自我欣赏。"},
    "圣杯十": {"artist": "Gustav Klimt", "title": "The Tree of Life", "year": 1909, "url": "https://www.belvedere.at/en/tree-life-gustav-klimt", "reason": "情感的圆满与多元和谐，呼应圣杯十中家庭和谐与共同幸福。"},
    # === 圣杯组 数字牌 逆位 ===
    "圣杯Ace · 逆位": {"artist": "J.M.W. Turner", "title": "The Harbor of Dieppe", "year": 1826, "url": "https://www.metmuseum.org/art/collection/search/437836", "reason": "情感之水的逆流与混乱，呼应圣杯Ace逆位中情感阻塞与灵感干涸。"},
    "圣杯二 · 逆位": {"artist": "Edward Hopper", "title": "Nighthawks", "year": 1942, "url": "https://www.artic.edu/artworks/111628", "reason": "关系失衡与疏离感，呼应圣杯二逆位中沟通断开与期望落空。"},
    "圣杯三 · 逆位": {"artist": "Georges Seurat", "title": "A Sunday on La Grande Jatte", "year": 1884, "url": "https://www.artic.edu/artworks/27992", "reason": "身在人群心在别处的疏离，呼应圣杯三逆位中欢庆中断与社交疏离。"},
    "圣杯四 · 逆位": {"artist": "Vincent van Gogh", "title": "The Yellow House", "year": 1888, "url": "https://www.vangoghmuseum.nl/en/collection/s0032V1962", "reason": "被动改变与走出停滞的第一步，呼应圣杯四逆位中尝试接受。"},
    "圣杯五 · 逆位": {"artist": "Claude Monet", "title": "Water Lilies", "year": 1906, "url": "https://www.artic.edu/artworks/16568", "reason": "疗愈中的水面与希望，呼应圣杯五逆位中走出悲伤与看见希望。"},
    "圣杯六 · 逆位": {"artist": "Claude Monet", "title": "Water Lilies", "year": 1906, "url": "https://www.artic.edu/artworks/16568", "reason": "回忆与当下的流动，呼应圣杯六逆位中沉溺过往与走出舒适。"},
    "圣杯七 · 逆位": {"artist": "Johannes Vermeer", "title": "Young Woman with a Water Pitcher", "year": 1662, "url": "https://www.metmuseum.org/art/collection/search/437880", "reason": "务实与清晰的选择，呼应圣杯七逆位中清晰欲望与面对现实。"},
    "圣杯八 · 逆位": {"artist": "Caspar David Friedrich", "title": "The Sea of Ice", "year": 1824, "url": "https://www.metmuseum.org/art/collection/search/438417", "reason": "目标模糊与犹豫不决，呼应圣杯八逆位中恐惧离开与目标模糊。"},
    "圣杯九 · 逆位": {"artist": "Johannes Vermeer", "title": "Young Woman with a Water Pitcher", "year": 1662, "url": "https://www.metmuseum.org/art/collection/search/437880", "reason": "外在满足与内在渴望的落差，呼应圣杯九逆位中愿望落空与寻找深层满足。"},
    "圣杯十 · 逆位": {"artist": "Rembrandt", "title": "The Return of the Prodigal Son", "year": 1669, "url": "https://www.metmuseum.org/art/collection/search/437394", "reason": "和谐破裂与修补裂痕，呼应圣杯十逆位中家庭失和与共同目标缺失。"},
    # === 宝剑组 数字牌 正位 ===
    "宝剑Ace": {"artist": "Michelangelo", "title": "The Creation of Adam", "year": 1512, "url": "https://www.museivaticani.va/content/museivaticani/en/collezioni/musei/cappella-sistina.html", "reason": "突破迷雾的清明与创生，呼应宝剑Ace中心智突破与果断决策。"},
    "宝剑二": {"artist": "Johannes Vermeer", "title": "Girl with a Pearl Earring", "year": 1665, "url": "https://www.mauritshuis.nl/en/our-collection/artworks/670-girl-with-a-pearl-earring", "reason": "双手交叉的回避与僵局，呼应宝剑二中思想僵局与艰难抉择。"},
    "宝剑三": {"artist": "Rembrandt", "title": "The Return of the Prodigal Son", "year": 1669, "url": "https://www.metmuseum.org/art/collection/search/437394", "reason": "心痛与接纳伤害的慈悲，呼应宝剑三中正视心痛与情感认知。"},
    "宝剑四": {"artist": "Édouard Manet", "title": "The Rest", "year": 1870, "url": "https://www.artic.edu/artworks/20684", "reason": "主动休憩与心智恢复，呼应宝剑四中主动休整与身心恢复。"},
    "宝剑五": {"artist": "Jacques-Louis David", "title": "The Death of Socrates", "year": 1787, "url": "https://www.metmuseum.org/art/collection/search/436105", "reason": "争论胜负与代价反思，呼应宝剑五中赢了争论是否输了和气的检视。"},
    "宝剑六": {"artist": "Claude Monet", "title": "Bathers at La Grenouillère", "year": 1869, "url": "https://www.metmuseum.org/art/collection/search/437134", "reason": "渡水与平稳过渡，呼应宝剑六中带着伤痛逐渐离开困境、平稳过渡。"},
    "宝剑七": {"artist": "Hieronymus Bosch", "title": "The Garden of Earthly Delights", "year": 1510, "url": "https://www.museodelprado.es/en/the-collection/art-works/the-garden-of-earthly-delights-triptych/02388242-6d6a-4e9e-a992-e1311eab3609", "reason": "机敏与另辟蹊径的张力，呼应宝剑七中智取策略与潜在风险。"},
    "宝剑八": {"artist": "Rembrandt", "title": "The Philosopher in Meditation", "year": 1632, "url": "https://www.metmuseum.org/art/collection/search/437394", "reason": "自我设限与认知解放，呼应宝剑八中思想束缚与认知解放。"},
    "宝剑九": {"artist": "Edvard Munch", "title": "The Scream", "year": 1893, "url": "https://www.moma.org/collection/works/60075", "reason": "深夜恐惧与焦虑外显，呼应宝剑九中思维焦虑与压力显现。"},
    "宝剑十": {"artist": "Vincent van Gogh", "title": "Wheatfield with Crows", "year": 1890, "url": "https://www.vangoghmuseum.nl/en/collection/s0149V1962", "reason": "痛苦终结与黎明将至，呼应宝剑十中触底与彻底放下的希望信号。"},
    # === 宝剑组 数字牌 逆位 ===
    "宝剑Ace · 逆位": {"artist": "J.M.W. Turner", "title": "The Harbor of Dieppe", "year": 1826, "url": "https://www.metmuseum.org/art/collection/search/437836", "reason": "思维混乱与真理扭曲，呼应宝剑Ace逆位中决策失误与真理扭曲。"},
    "宝剑二 · 逆位": {"artist": "J.M.W. Turner", "title": "Rain, Steam and Speed", "year": 1844, "url": "https://www.nationalgallery.org.uk/paintings/joseph-mallord-william-turner-rain-steam-and-speed-the-great-western-railway", "reason": "僵局打破与情绪决堤，呼应宝剑二逆位中被迫选择与僵局打破。"},
    "宝剑三 · 逆位": {"artist": "Rembrandt", "title": "Aristotle with a Bust of Homer", "year": 1653, "url": "https://www.metmuseum.org/art/collection/search/437394", "reason": "情感隔离与旧伤浮现，呼应宝剑三逆位中拒绝痛苦与温柔面对。"},
    "宝剑四 · 逆位": {"artist": "Vincent van Gogh", "title": "The Starry Night", "year": 1889, "url": "https://www.moma.org/collection/works/79802", "reason": "内心不宁与被迫行动，呼应宝剑四逆位中休息中断与内心不宁。"},
    "宝剑五 · 逆位": {"artist": "Pierre-Auguste Renoir", "title": "The Umbrellas", "year": 1886, "url": "https://www.nationalgallery.org.uk/paintings/pierre-auguste-renoir-the-umbrellas", "reason": "愿意和解与关系修复，呼应宝剑五逆位中无意义胜利与愿意和解。"},
    "宝剑六 · 逆位": {"artist": "Winslow Homer", "title": "The Gulf Stream", "year": 1899, "url": "https://www.metmuseum.org/art/collection/search/11122", "reason": "颠簸的过渡与旧伤难愈，呼应宝剑六逆位中过渡艰难与行程受阻。"},
    "宝剑七 · 逆位": {"artist": "Johannes Vermeer", "title": "Young Woman with a Water Pitcher", "year": 1662, "url": "https://www.metmuseum.org/art/collection/search/437880", "reason": "回归诚实与直接，呼应宝剑七逆位中计谋失败与回归正道。"},
    "宝剑八 · 逆位": {"artist": "Caspar David Friedrich", "title": "Morning in the Riesengebirge", "year": 1811, "url": "https://www.metmuseum.org/art/collection/search/438417", "reason": "看见出路与尝试挣脱，呼应宝剑八逆位中认识束缚与看见出路。"},
    "宝剑九 · 逆位": {"artist": "Claude Monet", "title": "Impression, Sunrise", "year": 1872, "url": "https://www.metmuseum.org/art/collection/search/437106", "reason": "恐惧具象与曙光初现，呼应宝剑九逆位中寻求倾诉与曙光初现。"},
    "宝剑十 · 逆位": {"artist": "Vincent van Gogh", "title": "Starry Night Over the Rhône", "year": 1888, "url": "https://www.musee-orsay.fr/en/collections/works-in-focus/search/commentaire_id/la-nuit-etoilee-7100.html", "reason": "黎明降临与痛苦终结，呼应宝剑十逆位中触底反弹与黎明降临。"},
    # === 星币组 数字牌 正位 ===
    "星币Ace": {"artist": "Jean-François Millet", "title": "The Sower", "year": 1851, "url": "https://www.metmuseum.org/art/collection/search/363029", "reason": "物质世界的新种子与务实起点，呼应星币Ace中财富种子与身体关注。"},
    "星币二": {"artist": "Edgar Degas", "title": "The Dance Class", "year": 1874, "url": "https://www.metmuseum.org/art/collection/search/438817", "reason": "平衡与多任务的艺术，呼应星币二中财务平衡与灵活应对。"},
    "星币三": {"artist": "Raphael", "title": "The School of Athens", "year": 1511, "url": "https://www.museivaticani.va/content/museivaticani/en/collezioni/musei/stanze-di-raffaello/stanza-della-segnatura/scuola-di-atene.html", "reason": "团队协作与技艺磨练，呼应星币三中扎实学习与各展所长。"},
    "星币四": {"artist": "Jan van Eyck", "title": "The Arnolfini Portrait", "year": 1434, "url": "https://www.nationalgallery.org.uk/paintings/jan-van-eyck-the-arnolfini-portrait", "reason": "稳固持有与安全感，呼应星币四中财务保守与建立安全感。"},
    "星币五": {"artist": "Vincent van Gogh", "title": "The Potato Eaters", "year": 1885, "url": "https://www.vangoghmuseum.nl/en/collection/s0009V1962", "reason": "困境中的陪伴与希望，呼应星币五中财务困难与困境中的陪伴。"},
    "星币六": {"artist": "Pieter Bruegel the Elder", "title": "The Harvesters", "year": 1565, "url": "https://www.metmuseum.org/art/collection/search/435809", "reason": "施与受的平衡与公平，呼应星币六中慷慨分享与资源流动。"},
    "星币七": {"artist": "Pieter Bruegel the Elder", "title": "The Harvesters", "year": 1565, "url": "https://www.metmuseum.org/art/collection/search/435809", "reason": "收获与评估期，呼应星币七中评估收获与长远规划。"},
    "星币八": {"artist": "Vermeer", "title": "The Astronomer", "year": 1668, "url": "https://www.louvre.fr/en/oeuvre-notices/astronomer", "reason": "潜心钻研与精益求精，呼应星币八中技艺钻研与技能提升。"},
    "星币九": {"artist": "Claude Monet", "title": "Woman with a Parasol", "year": 1875, "url": "https://www.nga.gov/collection/art-object-page.61379.html", "reason": "享受成果与自我满足，呼应星币九中自律有成与财务独立。"},
    "星币十": {"artist": "Thomas Gainsborough", "title": "Mr and Mrs Andrews", "year": 1750, "url": "https://www.nationalgallery.org.uk/paintings/thomas-gainsborough-mr-and-mrs-andrews", "reason": "家族丰盛与财富根基，呼应星币十中财富稳固与事业根基。"},
    # === 星币组 数字牌 逆位 ===
    "星币Ace · 逆位": {"artist": "Hieronymus Bosch", "title": "The Temptation of St Anthony", "year": 1501, "url": "https://www.museodelprado.es/en/the-collection/art-works/the-temptation-of-st-anthony/2dc4302a-b772-4d69-9f6a-2dc77a17ee7f", "reason": "机会不稳与审慎评估，呼应星币Ace逆位中机会不稳与避免匆忙开始。"},
    "星币二 · 逆位": {"artist": "J.M.W. Turner", "title": "Rain, Steam and Speed", "year": 1844, "url": "https://www.nationalgallery.org.uk/paintings/joseph-mallord-william-turner-rain-steam-and-speed-the-great-western-railway", "reason": "平衡失控与失去节奏，呼应星币二逆位中财务混乱与优先排序。"},
    "星币三 · 逆位": {"artist": "Edward Hopper", "title": "Office at Night", "year": 1940, "url": "https://walkerart.org/collections/artworks/office-at-night", "reason": "合作不和与沟通问题，呼应星币三逆位中合作不和与技艺不精。"},
    "星币四 · 逆位": {"artist": "Gustav Klimt", "title": "The Kiss", "year": 1908, "url": "https://www.belvedere.at/en/kiss-gustav-klimt", "reason": "持有与流动的平衡，呼应星币四逆位中过度掌控与安全感缺失。"},
    "星币五 · 逆位": {"artist": "Vincent van Gogh", "title": "The Starry Night", "year": 1889, "url": "https://www.moma.org/collection/works/79802", "reason": "境遇改善与接受援助，呼应星币五逆位中走出孤立与接受援助。"},
    "星币六 · 逆位": {"artist": "Rembrandt", "title": "The Anatomy Lesson of Dr. Nicolaes Tulp", "year": 1632, "url": "https://www.mauritshuis.nl/en/our-collection/artworks/146-the-anatomy-lesson-of-dr-nicolaes-tulp", "reason": "权力操控与交易不公，呼应星币六逆位中权力操控与依赖共生。"},
    "星币七 · 逆位": {"artist": "Claude Monet", "title": "Poppy Field", "year": 1873, "url": "https://www.metmuseum.org/art/collection/search/437106", "reason": "耐心不足与重新评估，呼应星币七逆位中评估失误与耐心不足。"},
    "星币八 · 逆位": {"artist": "Vincent van Gogh", "title": "The Potato Eaters", "year": 1885, "url": "https://www.vangoghmuseum.nl/en/collection/s0009V1962", "reason": "动力缺乏与寻找意义感，呼应星币八逆位中动力缺乏与技艺荒废。"},
    "星币九 · 逆位": {"artist": "Vincent van Gogh", "title": "The Bedroom", "year": 1888, "url": "https://www.artic.edu/artworks/195846", "reason": "内心孤独与价值空虚，呼应星币九逆位中内心孤独与过度依赖物质。"},
    "星币十 · 逆位": {"artist": "Thomas Cole", "title": "The Course of Empire: Destruction", "year": 1836, "url": "https://www.metmuseum.org/art/collection/search/692371", "reason": "根基动摇与及早审视，呼应星币十逆位中根基动摇与家族失和。"},
    # === 宫廷牌 正位 ===
    "权杖侍从": {"artist": "Mary Cassatt", "title": "The Child's Bath", "year": 1893, "url": "https://www.artic.edu/artworks/111442", "reason": "好奇心与天真活力，呼应权杖侍从中探索热情与新开端。"},
    "权杖骑士": {"artist": "Eugène Delacroix", "title": "Liberty Leading the People", "year": 1830, "url": "https://www.metmuseum.org/art/collection/search/459974", "reason": "勇往直前与目标追求，呼应权杖骑士中积极行动与勇往直前。"},
    "权杖皇后": {"artist": "Pierre-Auguste Renoir", "title": "Luncheon of the Boating Party", "year": 1881, "url": "https://www.phillipscollection.org/collection/luncheon-boating-party", "reason": "滋养热情与自信吸引力，呼应权杖皇后中滋养热情与持续发光。"},
    "权杖国王": {"artist": "Jacques-Louis David", "title": "The Coronation of Napoleon", "year": 1807, "url": "https://artsandculture.google.com/asset/jacques-louis-david-the-coronation-of-napoleon/NAG5bD_bzEVQ3Q", "reason": "统御行动与领导力，呼应权杖国王中企业家精神与远见。"},
    "圣杯侍从": {"artist": "Johannes Vermeer", "title": "Girl with a Pearl Earring", "year": 1665, "url": "https://www.mauritshuis.nl/en/our-collection/artworks/670-girl-with-a-pearl-earring", "reason": "情感萌芽与敏感敞开，呼应圣杯侍从中对美的觉察与敞开。"},
    "圣杯骑士": {"artist": "Gustav Klimt", "title": "The Kiss", "year": 1908, "url": "https://www.belvedere.at/en/kiss-gustav-klimt", "reason": "情感追随与浪漫理想主义，呼应圣杯骑士中追随内心的方向。"},
    "圣杯皇后": {"artist": "Mary Cassatt", "title": "The Child's Bath", "year": 1893, "url": "https://www.artic.edu/artworks/111442", "reason": "滋养情感与共情直觉，呼应圣杯皇后中无条件的爱与深度共情。"},
    "圣杯国王": {"artist": "Rembrandt", "title": "Aristotle with a Bust of Homer", "year": 1653, "url": "https://www.metmuseum.org/art/collection/search/437394", "reason": "情感成熟与稳定支持，呼应圣杯国王中统御情感与成熟稳重。"},
    "宝剑侍从": {"artist": "Raphael", "title": "The School of Athens", "year": 1511, "url": "https://www.museivaticani.va/content/museivaticani/en/collezioni/musei/stanze-di-raffaello/stanza-della-segnatura/scuola-di-atene.html", "reason": "思维好奇与信息吸收，呼应宝剑侍从中敏锐学习与提问。"},
    "宝剑骑士": {"artist": "Eugène Delacroix", "title": "The Death of Sardanapalus", "year": 1827, "url": "https://www.metmuseum.org/art/collection/search/436134", "reason": "思维迅捷与直言不讳，呼应宝剑骑士中为真理直抒胸臆。"},
    "宝剑皇后": {"artist": "Johannes Vermeer", "title": "Young Woman with a Water Pitcher", "year": 1662, "url": "https://www.metmuseum.org/art/collection/search/437880", "reason": "思维清晰而慈悲，呼应宝剑皇后中洞察本质与温和沟通。"},
    "宝剑国王": {"artist": "Rembrandt", "title": "The Anatomy Lesson of Dr. Nicolaes Tulp", "year": 1632, "url": "https://www.mauritshuis.nl/en/our-collection/artworks/146-the-anatomy-lesson-of-dr-nicolaes-tulp", "reason": "理性果断与智慧权威，呼应宝剑国王中刚正不苟言笑的决断仪态。"},
    "星币侍从": {"artist": "Vermeer", "title": "The Astronomer", "year": 1668, "url": "https://www.louvre.fr/en/oeuvre-notices/astronomer", "reason": "踏实学习与务实钻研，呼应星币侍从中耐心打磨与一步一个脚印。"},
    "星币骑士": {"artist": "Pieter Bruegel the Elder", "title": "The Harvesters", "year": 1565, "url": "https://www.metmuseum.org/art/collection/search/435809", "reason": "专注稳健与长远耕耘，呼应星币骑士中务实行动与不轻易放弃。"},
    "星币皇后": {"artist": "Claude Monet", "title": "Woman with a Parasol", "year": 1875, "url": "https://www.nga.gov/collection/art-object-page.61379.html", "reason": "丰盛感知与分享美好，呼应星币皇后中滋养物质与丰盛感。"},
    "星币国王": {"artist": "Rembrandt", "title": "Aristotle with a Bust of Homer", "year": 1653, "url": "https://www.metmuseum.org/art/collection/search/437394", "reason": "稳健可靠与管理审慎，呼应星币国王中统御物质与长远眼光。"},
    # === 宫廷牌 逆位 ===
    "权杖侍从 · 逆位": {"artist": "Claude Monet", "title": "Impression, Sunrise", "year": 1872, "url": "https://www.metmuseum.org/art/collection/search/437106", "reason": "热情散漫与找回初学者的乐趣，呼应权杖侍从逆位中热情易逝与害怕失败。"},
    "权杖骑士 · 逆位": {"artist": "J.M.W. Turner", "title": "The Burning of the Houses of Lords and Commons", "year": 1834, "url": "https://www.artic.edu/artworks/61925", "reason": "冲动鲁莽与能量失控，呼应权杖骑士逆位中急躁欠考虑与燃错方向。"},
    "权杖皇后 · 逆位": {"artist": "Gustav Klimt", "title": "Judith and the Head of Holofernes", "year": 1901, "url": "https://www.belvedere.at/en/judith-and-head-holofernes-gustav-klimt", "reason": "掌控欲强与热情变专制，呼应权杖皇后逆位中自信变傲慢。"},
    "权杖国王 · 逆位": {"artist": "Jacques-Louis David", "title": "The Death of Marat", "year": 1793, "url": "https://www.fine-arts-museum.be/en/the-museums/collections/object_2477", "reason": "刚愎自用与缺乏包容，呼应权杖国王逆位中领导力沦为独裁。"},
    "圣杯侍从 · 逆位": {"artist": "Vincent van Gogh", "title": "The Starry Night", "year": 1889, "url": "https://www.moma.org/collection/works/79802", "reason": "情感脆弱与过度敏感，呼应圣杯侍从逆位中沉溺幻想与不成熟。"},
    "圣杯骑士 · 逆位": {"artist": "Vincent van Gogh", "title": "The Bedroom", "year": 1888, "url": "https://www.artic.edu/artworks/195846", "reason": "易受情绪牵动与逃避承诺，呼应圣杯骑士逆位中感情用事与忧郁自怜。"},
    "圣杯皇后 · 逆位": {"artist": "Gustav Klimt", "title": "Portrait of Adele Bloch-Bauer I", "year": 1907, "url": "https://www.neuegalerie.org/collection/artist-pages/gustav-klimt-adele-bloch-bauer-i-1907", "reason": "情感边界模糊与共情过度，呼应圣杯皇后逆位中关爱变压力。"},
    "圣杯国王 · 逆位": {"artist": "Caspar David Friedrich", "title": "The Sea of Ice", "year": 1824, "url": "https://www.metmuseum.org/art/collection/search/438417", "reason": "情感隔离与冷漠疏离，呼应圣杯国王逆位中以理性压抑情感。"},
    "宝剑侍从 · 逆位": {"artist": "Hieronymus Bosch", "title": "The Garden of Earthly Delights", "year": 1510, "url": "https://www.museodelprado.es/en/the-collection/art-works/the-garden-of-earthly-delights-triptych/02388242-6d6a-4e9e-a992-e1311eab3609", "reason": "思维偏激与传播未经核实的信息，呼应宝剑侍从逆位中学习浅薄。"},
    "宝剑骑士 · 逆位": {"artist": "Caravaggio", "title": "David with the Head of Goliath", "year": 1610, "url": "https://www.galleriaborghese.it/en/collezioni/opera/david-con-la-testa-di-golia", "reason": "言语伤人与尖刻言论，呼应宝剑骑士逆位中思维化为利刃。"},
    "宝剑皇后 · 逆位": {"artist": "Artemisia Gentileschi", "title": "Judith Slaying Holofernes", "year": 1620, "url": "https://www.uffizi.it/en/artworks/judith-and-holofernes", "reason": "批判过度与洞察变审判，呼应宝剑皇后逆位中心智无法与慈悲结合。"},
    "宝剑国王 · 逆位": {"artist": "Francisco Goya", "title": "Saturn Devouring His Son", "year": 1823, "url": "https://www.museodelprado.es/en/the-collection/art-work/saturn/18134a75-9e3c-4276-959e-0d47d80c0b4c", "reason": "思维专制与滥用权威，呼应宝剑国王逆位中智慧沦为操控工具。"},
    "星币侍从 · 逆位": {"artist": "Pieter Bruegel the Elder", "title": "The Harvesters", "year": 1565, "url": "https://www.metmuseum.org/art/collection/search/435809", "reason": "学习怠惰与好逸恶劳，呼应星币侍从逆位中缺乏耐心与敷衍拖延。"},
    "星币骑士 · 逆位": {"artist": "Vincent van Gogh", "title": "The Potato Eaters", "year": 1885, "url": "https://www.vangoghmuseum.nl/en/collection/s0009V1962", "reason": "停滞不前与自我审视，呼应星币骑士逆位中雄心但不坚持与工作生活分开。"},
    "星币皇后 · 逆位": {"artist": "Gustav Klimt", "title": "Portrait of Adele Bloch-Bauer I", "year": 1907, "url": "https://www.neuegalerie.org/collection/artist-pages/gustav-klimt-adele-bloch-bauer-i-1907", "reason": "价值迷失与过度追求物质，呼应星币皇后逆位中忽视内在价值。"},
    "星币国王 · 逆位": {"artist": "Rembrandt", "title": "The Prodigal Son", "year": 1669, "url": "https://www.metmuseum.org/art/collection/search/437394", "reason": "管理失当与僵化贪婪，呼应星币国王逆位中稳健变固执与审慎变恐惧。"},
}
